import { cookies } from "next/headers";
import { NextResponse } from "next/server";
import { createOptionalClient } from "@/lib/supabase/server";
import { isAllowedEmail } from "@/lib/auth/email";
import { readGitHubSession } from "@/lib/github/session";

interface GitHubPushFile {
  path: string;
  content: string;
}

interface GitHubPushRequest {
  token?: string;
  owner?: string;
  repo: string;
  branch?: string;
  privateRepo?: boolean;
  message?: string;
  files: GitHubPushFile[];
  alwaysCreateNewRepo?: boolean;
}

interface GitHubUser {
  login: string;
}

interface GitHubRepo {
  name: string;
  full_name: string;
  html_url: string;
  default_branch: string;
  owner: { login: string };
}

interface GitHubRef {
  object: { sha: string };
}

interface GitHubCommit {
  sha: string;
  html_url: string;
  tree: { sha: string };
}

interface GitHubTree {
  sha: string;
}

function normalizeRepoName(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 100);
}

function normalizeBranchName(value: string | undefined): string {
  return (value || "main")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/^refs\/heads\//, "")
    .replace(/^\/+|\/+$/g, "") || "main";
}

function normalizePath(path: string): string | null {
  const cleaned = path.trim().replace(/^\/+/, "");
  if (!cleaned || cleaned.includes("..") || cleaned.startsWith(".env")) return null;
  return cleaned;
}

function encodeGitRef(ref: string): string {
  return ref.split("/").map(encodeURIComponent).join("/");
}

async function githubFetch<T>(
  token: string,
  path: string,
  init: RequestInit = {}
): Promise<T> {
  const response = await fetch(`https://api.github.com${path}`, {
    ...init,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
      ...(init.headers ?? {}),
    },
  });

  if (!response.ok) {
    let detail = `${response.status} ${response.statusText}`;
    try {
      const json = await response.json();
      if (typeof json?.message === "string") detail = json.message;
    } catch {
      // Keep status text.
    }
    throw new Error(detail);
  }

  return response.json() as Promise<T>;
}

async function githubFetchMaybe<T>(
  token: string,
  path: string,
  init: RequestInit = {}
): Promise<{ ok: true; data: T } | { ok: false; status: number; message: string }> {
  const response = await fetch(`https://api.github.com${path}`, {
    ...init,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
      ...(init.headers ?? {}),
    },
  });

  if (!response.ok) {
    let message = `${response.status} ${response.statusText}`;
    try {
      const json = await response.json();
      if (typeof json?.message === "string") message = json.message;
    } catch {
      // Keep status text.
    }
    return { ok: false, status: response.status, message };
  }

  return { ok: true, data: await response.json() as T };
}

async function sleep(ms: number): Promise<void> {
  await new Promise((resolve) => setTimeout(resolve, ms));
}

function pickUniqueRepoName(base: string, suffixCount: number): string {
  const trimmed = base.replace(/-+$/g, "").slice(0, 80);
  if (suffixCount === 0) return trimmed;
  return `${trimmed}-${suffixCount + 1}`.slice(0, 100);
}

async function createRepoFresh({
  token,
  owner,
  repo,
  privateRepo,
  user,
}: {
  token: string;
  owner: string;
  repo: string;
  privateRepo: boolean;
  user: GitHubUser;
}): Promise<GitHubRepo> {
  const body = JSON.stringify({
    name: repo,
    private: privateRepo,
    auto_init: true,
    description: "Generated by Nutrient Demo Studio",
  });
  if (owner.toLowerCase() === user.login.toLowerCase()) {
    return githubFetch<GitHubRepo>(token, "/user/repos", { method: "POST", body });
  }
  return githubFetch<GitHubRepo>(token, `/orgs/${owner}/repos`, { method: "POST", body });
}

async function ensureRepo({
  token,
  owner,
  repo,
  privateRepo,
  user,
  alwaysCreateNewRepo,
}: {
  token: string;
  owner: string;
  repo: string;
  privateRepo: boolean;
  user: GitHubUser;
  alwaysCreateNewRepo: boolean;
}): Promise<GitHubRepo> {
  // When alwaysCreateNewRepo is true (the default for export pushes), find a free name and
  // create a brand-new repo. This prevents the Studio from accidentally pushing on top of
  // the user's existing repos (which can overwrite real work like the Studio's own repo).
  if (alwaysCreateNewRepo) {
    for (let attempt = 0; attempt < 20; attempt += 1) {
      const candidate = pickUniqueRepoName(repo, attempt);
      const probe = await githubFetchMaybe<GitHubRepo>(token, `/repos/${owner}/${candidate}`);
      if (probe.ok) continue;
      if (probe.status !== 404) throw new Error(probe.message);
      return createRepoFresh({ token, owner, repo: candidate, privateRepo, user });
    }
    throw new Error("Could not find a free repository name after 20 attempts.");
  }

  const existing = await githubFetchMaybe<GitHubRepo>(token, `/repos/${owner}/${repo}`);
  if (existing.ok) return existing.data;
  if (existing.status !== 404) throw new Error(existing.message);
  return createRepoFresh({ token, owner, repo, privateRepo, user });
}

async function getBranchRef(token: string, owner: string, repo: string, branch: string) {
  return githubFetchMaybe<GitHubRef>(
    token,
    `/repos/${owner}/${repo}/git/ref/heads/${encodeGitRef(branch)}`
  );
}

async function ensureBranch({
  token,
  owner,
  repo,
  branch,
  defaultBranch,
}: {
  token: string;
  owner: string;
  repo: string;
  branch: string;
  defaultBranch: string;
}): Promise<GitHubRef> {
  for (let attempt = 0; attempt < 4; attempt += 1) {
    const target = await getBranchRef(token, owner, repo, branch);
    if (target.ok) return target.data;

    const base = await getBranchRef(token, owner, repo, defaultBranch);
    if (base.ok) {
      if (branch === defaultBranch) return base.data;

      return githubFetch<GitHubRef>(token, `/repos/${owner}/${repo}/git/refs`, {
        method: "POST",
        body: JSON.stringify({
          ref: `refs/heads/${branch}`,
          sha: base.data.object.sha,
        }),
      });
    }

    await sleep(500);
  }

  throw new Error("Could not find or create a branch for this repository.");
}

export async function POST(req: Request) {
  const supabase = await createOptionalClient();
  if (!supabase) return NextResponse.json({ error: "Supabase is not configured." }, { status: 503 });

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user || !isAllowedEmail(user.email)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: GitHubPushRequest;
  try {
    body = await req.json() as GitHubPushRequest;
  } catch {
    return NextResponse.json({ error: "Invalid JSON request body." }, { status: 400 });
  }

  const githubSession = readGitHubSession(await cookies());
  const token = body.token?.trim() || githubSession?.accessToken;
  const repo = normalizeRepoName(body.repo ?? "");
  const branch = normalizeBranchName(body.branch);
  const message = body.message?.trim() || "Initial commit from Nutrient Demo Studio";

  if (!token || !repo || !Array.isArray(body.files) || body.files.length === 0) {
    return NextResponse.json({ error: "Connect GitHub first, or provide a GitHub token, repo, and files." }, { status: 400 });
  }

  const files = body.files
    .map((file) => {
      const path = normalizePath(file.path);
      if (!path) return null;
      return { path, content: file.content ?? "" };
    })
    .filter((file): file is GitHubPushFile => Boolean(file));

  if (!files.length) {
    return NextResponse.json({ error: "No valid project files to push." }, { status: 400 });
  }

  const filesByPath = new Map(files.map((file) => [file.path, file]));

  // Placeholders only — the real demo token is never pushed to GitHub. Users
  // grab theirs from workspace settings (Backend Processing → demo token) or
  // point VITE_BACKEND_URL at their own deployed backend (see backend/).
  filesByPath.set(".env.local.example", {
    path: ".env.local.example",
    content: [
      "# Nutrient Web SDK license (https://www.nutrient.io/web/)",
      "VITE_NUTRIENT_LICENSE_KEY=your-license-key-here",
      "",
      "# Backend processing — option A: Nucode managed backend",
      "# Copy the proxy URL + demo token from your Nucode workspace settings (Backend Processing)",
      "# VITE_BACKEND_URL=https://<nucode-host>/api/backend-proxy/<workspace-id>",
      "# VITE_BACKEND_TOKEN=ndk_...",
      "",
      "# Backend processing — option B: your own backend (see backend/ folder)",
      "# VITE_BACKEND_URL=http://localhost:8000",
      "",
    ].join("\n"),
  });
  filesByPath.set(".gitignore", {
    path: ".gitignore",
    content: "node_modules\ndist\n.env\n.env.local\n.DS_Store\n",
  });
  const exportFiles = Array.from(filesByPath.values());

  // Validate the token up-front so an expired session surfaces a clean re-auth signal
  // instead of failing deep inside ensureRepo with a confusing 401.
  try {
    const userProbe = await githubFetchMaybe<GitHubUser>(token, "/user");
    if (!userProbe.ok && (userProbe.status === 401 || userProbe.status === 403)) {
      return NextResponse.json(
        { error: "GitHub session expired. Reconnect to push.", reauthRequired: true },
        { status: 401 }
      );
    }
    if (!userProbe.ok) {
      return NextResponse.json({ error: userProbe.message }, { status: userProbe.status });
    }
  } catch (error) {
    const messageText = error instanceof Error ? error.message : "Could not verify GitHub session.";
    return NextResponse.json({ error: messageText, reauthRequired: true }, { status: 401 });
  }

  try {
    const githubUser = await githubFetch<GitHubUser>(token, "/user");
    const owner = (body.owner?.trim() || githubUser.login).replace(/^@/, "");
    const repoInfo = await ensureRepo({
      token,
      owner,
      repo,
      privateRepo: body.privateRepo ?? true,
      user: githubUser,
      alwaysCreateNewRepo: body.alwaysCreateNewRepo ?? true,
    });

    const targetBranch = branch || repoInfo.default_branch || "main";
    const ref = await ensureBranch({
      token,
      owner: repoInfo.owner.login,
      repo: repoInfo.name,
      branch: targetBranch,
      defaultBranch: repoInfo.default_branch || "main",
    });

    const baseCommit = await githubFetch<GitHubCommit>(
      token,
      `/repos/${repoInfo.owner.login}/${repoInfo.name}/git/commits/${ref.object.sha}`
    );

    const tree = await githubFetch<GitHubTree>(
      token,
      `/repos/${repoInfo.owner.login}/${repoInfo.name}/git/trees`,
      {
        method: "POST",
        body: JSON.stringify({
          base_tree: baseCommit.tree.sha,
          tree: exportFiles.map((file) => ({
            path: file.path,
            mode: "100644",
            type: "blob",
            content: file.content,
          })),
        }),
      }
    );

    const commit = await githubFetch<GitHubCommit>(
      token,
      `/repos/${repoInfo.owner.login}/${repoInfo.name}/git/commits`,
      {
        method: "POST",
        body: JSON.stringify({
          message,
          tree: tree.sha,
          parents: [baseCommit.sha],
        }),
      }
    );

    await githubFetch<GitHubRef>(
      token,
      `/repos/${repoInfo.owner.login}/${repoInfo.name}/git/refs/heads/${encodeGitRef(targetBranch)}`,
      {
        method: "PATCH",
        body: JSON.stringify({ sha: commit.sha }),
      }
    );

    return NextResponse.json({
      ok: true,
      repoFullName: repoInfo.full_name,
      repoUrl: repoInfo.html_url,
      branch: targetBranch,
      commitSha: commit.sha,
      commitUrl: commit.html_url,
      fileCount: exportFiles.length,
    });
  } catch (error) {
    const messageText = error instanceof Error ? error.message : "GitHub push failed.";
    return NextResponse.json({ error: messageText }, { status: 500 });
  }
}
