import type { Metadata } from "next";
import { Container } from "@/components/ui/container";
import { PageIntro } from "@/components/site/page-intro";

export const metadata: Metadata = {
  title: "Terms of Service — Ren AI",
  description: "Terms and conditions for using Ren AI services.",
};

export default function TermsPage() {
  return (
    <>
      <PageIntro
        eyebrow="Legal"
        title="Terms of Service."
        lede="The terms and conditions that govern your use of Ren AI products and services."
      />

      <Container className="py-20 md:py-28">
        <div className="max-w-2xl space-y-10 text-[15px] leading-[1.75] text-graphite">
          <section>
            <p className="font-mono text-[11px] uppercase tracking-eyebrow text-graphite-soft">
              Effective date · June 2026
            </p>
            <p className="mt-4">
              By using Ren AI services — including Ren Code, the API, and this
              website — you agree to these terms. Please read them.
            </p>
          </section>

          {[
            {
              title: "The service",
              body: "Ren AI provides software engineering tools powered by Astra. The service is in active development. Features, availability, and pricing may change.",
            },
            {
              title: "Your account",
              body: "You are responsible for maintaining the security of your account credentials. You may not share your account or use it in ways that violate these terms or applicable laws.",
            },
            {
              title: "Your repositories",
              body: "When you connect a GitHub repository, you grant Ren Code read access to that repository for the purpose of operating the service. We do not store your source code beyond what is required to complete a requested operation.",
            },
            {
              title: "Acceptable use",
              body: "You may use Ren AI services for lawful purposes. You may not use them to generate malicious code, circumvent security systems, violate intellectual property rights, or harm others.",
            },
            {
              title: "Intellectual property",
              body: "Code and pull requests generated by Ren Code in response to your requests belong to you. Ren AI retains ownership of its systems, models, and platform.",
            },
            {
              title: "Limitation of liability",
              body: "Ren AI is provided as-is. We make no warranties about availability or results. Our liability is limited to the amount you paid us in the past 12 months.",
            },
            {
              title: "Changes",
              body: "We may update these terms. Significant changes will be communicated by email. Continued use of the service after changes constitutes acceptance.",
            },
            {
              title: "Contact",
              body: "For questions about these terms, contact legal@ren.ai.",
            },
          ].map((section) => (
            <section key={section.title} className="border-t border-line pt-8">
              <h2 className="font-serif text-title text-ink">{section.title}</h2>
              <p className="mt-3 text-pretty">{section.body}</p>
            </section>
          ))}
        </div>
      </Container>
    </>
  );
}
